# tasks file for mariadb-client
---
- name: install | dependencies
  apt:
    name: "{{ mariadb_client_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - mariadb-client-install-dependencies

- name: install | additional
  apt:
    name: "{{ mariadb_client_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - mariadb-client-install-additional
