# tasks file for mariadb-client
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ percona_client_dependencies }}"
  tags:
    - mariadb-client-install-dependencies

- name: install | additional
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ percona_client_install }}"
  tags:
    - mariadb-client-install-additional
