# tasks file
---
- name: install | dependencies  # noqa args[module]
  ansible.builtin.apt:
    name: "{{ mariadb_client_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - mariadb-client-install-dependencies

- name: install | additional  # noqa args[module]
  ansible.builtin.apt:
    name: "{{ mariadb_client_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - mariadb-client-install-additional
