# tasks file
---
- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - mariadb-client
    - mariadb-client-install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - mariadb-client
    - mariadb-client-configure
