# tasks file for mariadb-client
---
- include: install.yml
  tags:
    - configuration
    - mariadb-client
    - mariadb-client-install

- include: configure.yml
  tags:
    - configuration
    - mariadb-client
    - mariadb-client-configure
